"""
Generate V2__seed_questions.sql from the prototype's global_questions.xlsx.

Run once; the generated SQL is committed. Re-run only if the source corpus
changes, and add the result as a NEW migration (V3, V4, ...) rather than
editing V2 - Flyway checksums applied migrations.

    pip install openpyxl
    python tools/seed_questions.py
"""
import io
import re
import uuid

import openpyxl

SOURCE = "AgriVoice/media/global_questions.xlsx"
TARGET = "src/main/resources/db/migration/V2__seed_questions.sql"


def norm(value):
    if value is None:
        return None
    collapsed = re.sub(r"\s+", " ", str(value)).strip()
    return collapsed or None


def main():
    sheet = openpyxl.load_workbook(SOURCE)["Sheet1"]
    seen, rows = set(), []
    for raw in sheet.iter_rows(min_row=2, values_only=True):
        question, subcategory, category = norm(raw[0]), norm(raw[1]), norm(raw[2])
        if not question or question in seen:
            continue
        seen.add(question)
        rows.append((str(uuid.uuid4()), question, category, subcategory))

    def quote(value):
        return f"$q${value}$q$" if value else "NULL"

    values = ",\n".join(
        f"  ('{qid}', {quote(text)}, {quote(cat)}, {quote(sub)}, 'ur', TRUE)"
        for qid, text, cat, sub in rows
    )
    sql = (
        "-- Seed the question corpus.\n"
        "-- Generated by tools/seed_questions.py from the prototype's\n"
        "-- media/global_questions.xlsx. Urdu (ur) agricultural advisory questions.\n"
        "-- Dollar-quoting ($q$) avoids escaping apostrophes in the source text.\n\n"
        "INSERT INTO question (id, text, category, subcategory, language, active) VALUES\n"
        f"{values};\n"
    )
    io.open(TARGET, "w", encoding="utf-8", newline="\n").write(sql)
    print(f"{len(rows)} questions -> {TARGET}")


if __name__ == "__main__":
    main()
